-- Analyze sales performance by customer country.
-- Granularity: one row represents one customer country.

WITH country_performance AS (
    SELECT
        CustomerCountry,

        -- Count unique customers and orders in each country.
        COUNT(DISTINCT CustomerID) AS CustomerCount,
        COUNT(DISTINCT OrderID) AS OrderCount,

        -- Count product lines and units sold.
        COUNT(*) AS SalesLineCount,
        SUM(Quantity) AS UnitsSold,

        -- Aggregate country-level financial metrics.
        ROUND(SUM(GrossRevenue), 2) AS GrossRevenue,
        ROUND(SUM(DiscountAmount), 2) AS DiscountAmount,
        ROUND(SUM(NetRevenue), 2) AS NetRevenue

    FROM sales_order_lines

    -- Produce one result row for each customer country.
    GROUP BY CustomerCountry
),

ranked_countries AS (
    SELECT
        CustomerCountry,
        CustomerCount,
        OrderCount,
        SalesLineCount,
        UnitsSold,
        GrossRevenue,
        DiscountAmount,
        NetRevenue,

        -- Calculate the average revenue generated by each order.
        ROUND(
            NetRevenue / NULLIF(OrderCount, 0),
            2
        ) AS AverageOrderValue,

        -- Calculate each country's contribution to global revenue.
        ROUND(
            NetRevenue
            / NULLIF(
                SUM(NetRevenue) OVER (),
                0
            )
            * 100,
            2
        ) AS GlobalRevenueSharePercent,

        -- Rank countries by net revenue.
        DENSE_RANK() OVER (
            ORDER BY NetRevenue DESC
        ) AS RevenueRank

    FROM country_performance
)

SELECT
    CustomerCountry,
    CustomerCount,
    OrderCount,
    SalesLineCount,
    UnitsSold,
    GrossRevenue,
    DiscountAmount,
    NetRevenue,
    AverageOrderValue,
    GlobalRevenueSharePercent,
    RevenueRank

FROM ranked_countries

ORDER BY
    RevenueRank,
    CustomerCountry;